CREATE TABLE `state` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `NAME` varchar(32) NOT NULL,
  `CODE` varchar(2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8;

CREATE TABLE `address` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ADDRESS1` varchar(128) NOT NULL,
  `ADDRESS2` varchar(128) DEFAULT NULL,
  `CITY` varchar(64) NOT NULL,
  `STATE` int(11) NOT NULL,
  `ZIP` varchar(10) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `State_Constraint_Id` (`STATE`),
  CONSTRAINT `State_Constraint_Id` FOREIGN KEY (`STATE`) REFERENCES `state` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_profile` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MONGO_USER_ID` int(64) NOT NULL,
  `ABOUT_ME` varchar(128) DEFAULT NULL,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ADDRESS_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `user_contraint` (`MONGO_USER_ID`),
  KEY `Address_constraint_Id` (`ADDRESS_ID`),
  CONSTRAINT `Address_constraint_Id` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `address` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=latin1;

CREATE TABLE `user_interests` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` varchar(45) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFIED_BY` varchar(45) DEFAULT NULL,
  `MODIFIED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `NAME` varchar(32) NOT NULL,
  `USER_PROFILE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `UserProfile_constraint_Id` (`USER_PROFILE_ID`),
  CONSTRAINT `UserProfile_constraint_Id` FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `user_profile` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;