insert into state (CODE,NAME,CREATED_BY,CREATED_DATE,MODIFIED_DATE) values 
('AL', 'Alabama','SYSTEM',now(),now()),
('AK', 'Alaska','SYSTEM',now(),now()),
('AZ', 'Arizona','SYSTEM',now(),now()),
('AR', 'Arkansas','SYSTEM',now(),now()),
('CA', 'California','SYSTEM',now(),now()),
('CO', 'Colorado','SYSTEM',now(),now()),
('CT', 'Connecticut','SYSTEM',now(),now()),
('DE', 'Delaware','SYSTEM',now(),now()),
('DC', 'District of Columbia','SYSTEM',now(),now()),
('FL', 'Florida','SYSTEM',now(),now()),
('GA', 'Georgia','SYSTEM',now(),now()),
('HI', 'Hawaii','SYSTEM',now(),now()),
('ID', 'Idaho','SYSTEM',now(),now()),
('IL', 'Illinois','SYSTEM',now(),now()),
('IN', 'Indiana','SYSTEM',now(),now()),
('IA', 'Iowa','SYSTEM',now(),now()),
('KS', 'Kansas','SYSTEM',now(),now()),
('KY', 'Kentucky','SYSTEM',now(),now()),
('LA', 'Louisiana','SYSTEM',now(),now()),
('ME', 'Maine','SYSTEM',now(),now()),
('MD', 'Maryland','SYSTEM',now(),now()),
('MA', 'Massachusetts','SYSTEM',now(),now()),
('MI', 'Michigan','SYSTEM',now(),now()),
('MN', 'Minnesota','SYSTEM',now(),now()),
('MS', 'Mississippi','SYSTEM',now(),now()),
('MO', 'Missouri','SYSTEM',now(),now()),
('MT', 'Montana','SYSTEM',now(),now()),
('NE', 'Nebraska','SYSTEM',now(),now()),
('NV', 'Nevada','SYSTEM',now(),now()),
('NH', 'New Hampshire','SYSTEM',now(),now()),
('NJ', 'New Jersey','SYSTEM',now(),now()),
('NM', 'New Mexico','SYSTEM',now(),now()),
('NY', 'New York','SYSTEM',now(),now()),
('NC', 'North Carolina','SYSTEM',now(),now()),
('ND', 'North Dakota','SYSTEM',now(),now()),
('OH', 'Ohio','SYSTEM',now(),now()),
('OK', 'Oklahoma','SYSTEM',now(),now()),
('OR', 'Oregon','SYSTEM',now(),now()),
('PA', 'Pennsylvania','SYSTEM',now(),now()),
('PR', 'Puerto Rico','SYSTEM',now(),now()),
('RI', 'Rhode Island','SYSTEM',now(),now()),
('SC', 'South Carolina','SYSTEM',now(),now()),
('SD', 'South Dakota','SYSTEM',now(),now()),
('TN', 'Tennessee','SYSTEM',now(),now()),
('TX', 'Texas','SYSTEM',now(),now()),
('UT', 'Utah','SYSTEM',now(),now()),
('VT', 'Vermont','SYSTEM',now(),now()),
('VA', 'Virginia','SYSTEM',now(),now()),
('WA', 'Washington','SYSTEM',now(),now()),
('WV', 'West Virginia','SYSTEM',now(),now()),
('WI', 'Wisconsin','SYSTEM',now(),now()),
('WY', 'Wyoming','SYSTEM',now(),now());